version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nextjs:
    build: .
    container_name: todolist
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  prisma:
    build: .
    container_name: prisma
    restart: on-failure
    depends_on:
      - db
    command: ["npx", "prisma", "migrate", "deploy"]

volumes:
  pgdata:
